apiVersion: batch/v1
kind: CronJob
metadata:
  name: base-image-check-and-rebuild
spec:
  schedule: "1 */12 * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: "cronjob-base-image-rebuild"
        spec:
          containers:
          - name: oc-tekton
            image: quay.io/marrober/devex-terminal-4:minimal-terminal-1.3
            command: ["curl",  "-k", "https://layers-git-layers.apps.skylake.demolab.local/"]
          restartPolicy: OnFailure
