apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: dl-quay-webhook-trigger
  namespace: myapp-ci
spec:
  params:
    - name: quay-io-account
      type: string
    - name: quay-io-repository
      type: string
    - name: tag
      type: string
    - name: production-event-listener-route
      type: string
  steps:
    - name: trigger-production-deployment
      script: >-
        #!/usr/bin/env bash

        set +x

        echo ""{\"repository\": \"$(params.quay-io-account)/$(params.quay-io-repository)\", \"docker_url\": \"$(params.quay-io-account)/$(params.quay-io-repository)\", \"updated_tags\": [\"$(params.tag)\"]}" $(params.production-event-listener-route)"

        curl -k -s -d - "{\"repository\": \"$(params.quay-io-account)/$(params.quay-io-repository)\", \"docker_url\": \"$(params.quay-io-account)/$(params.quay-io-repository)\", \"updated_tags\": [\"$(params.tag)\"]}" $(params.production-event-listener-route)

      image: registry.redhat.io/rhel8/buildah@sha256:6a68ece207bc5fd8db2dd5cc2d0b53136236fb5178eb5b71eebe5d07a3c33d13
      workingDir: /files/source
      resources: {}
  workspaces:
  - name: files
    mountPath: /files
