apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: set-commit-status
spec:
  params:
  - name: GIT_REPO
    type: string
  - name: REPO
    type: string
  - default: git-host-access-token
    name: GIT_TOKEN_SECRET_NAME
    type: string
  - default: token
    name: GIT_TOKEN_SECRET_KEY
    type: string
  - name: COMMIT_SHA
    type: string
  - name: DESCRIPTION
    type: string
  - name: CONTEXT
    type: string
  - name: STATE
    type: string
  steps:
  - name: show-params
    script: >
      #!/bin/sh

      echo "Git_REPO : " $(params.GIT_REPO)

      echo "REPO : " $(params.REPO)

      echo "GIT_TOKEN_SECRET_NAME : " $(params.GIT_TOKEN_SECRET_NAME)

      echo "GIT_TOKEN_SECRET_KEY : " $(params.GIT_TOKEN_SECRET_KEY)

      echo "COMMIT_SHA : " $(params.COMMIT_SHA)

      echo "DESCRIPTION : " $(params.DESCRIPTION)

      echo "CONTEXT : " $(params.CONTEXT)

      echo "STATE : " $(params.STATE)

    image: quay.io/redhat-developer/gitops-commit-status@sha256:ef5b3b242bf3b42a3a5d3ff74b3c7d495c608297b7428ae57b8ece10954e7546
  - name: set-commit-status
    env:
    - name: GITHOSTACCESSTOKEN
      valueFrom:
        secretKeyRef:
          key: $(params.GIT_TOKEN_SECRET_KEY)
          name: $(params.GIT_TOKEN_SECRET_NAME)
    image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
    resources: {}
    script: >
      #!/bin/sh

      curl -H 'Content-Type: application/json' -X POST -u $GITHOSTACCESSTOKEN:x-oauth-basic -d '{"state":"$(params.STATE)", "description":"$(params.DESCRIPTION)", "context":"$(params.CONTEXT)"}' https://api.github.com/repos/$(params.GIT_REPO)/statuses/$(params.COMMIT_SHA)





      # echo "curl -H 'Content-Type: application/json' -X POST https://$GITHOSTACCESSTOKEN:x-oauth-basic@api.github.com/repos/$(params.GIT_REPO)/statuses/$(params.COMMIT_SHA) \ "  > curl-cmd.sh
      # "-d '{\"state\":\"$(params.STATE)\", \"description\":\"$(params.DESCRIPTION)\", \"context\":\"$(params.CONTEXT)\"}'" >> curl-cmd.sh

      # cat curl-cmd.sh

      # chmod u+x curl-cmd.sh

      # sh ./curl-cmd.sh

      echo "completed"
